language: node_js

node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - "test ! -d node_modules || npm prune"

scripts:
  - npm run test
  - npm run build

# after_script:
#   - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

notifications:
  email:
    recipients:
      - dragos.cirjan+glasswingjs@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
